# Generated by Django 2.1 on 2018-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20180824_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='shelf.Author')),
                ('categories', models.ManyToManyField(to='shelf.BookCategory')),
            ],
        ),
    ]
