# Generated by Django 2.1 on 2018-08-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20180825_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
