# Generated by Django 2.1 on 2018-08-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20180825_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=17)),
            ],
        ),
        migrations.RemoveField(
            model_name='book_new',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book_new',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='bookedition',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookedition',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='edition',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Book_new',
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
        migrations.DeleteModel(
            name='BookEdition',
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelf.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelf.Publisher'),
        ),
    ]
